// Shared product data — in production, this would come from Supabase
const allProducts = [
  {
    id: 1,
    name: 'Kerala Kasavu Saree',
    price: 2499,
    originalPrice: 3499,
    image: '/product-kasavu-saree.png',
    images: [
      '/product-kasavu-saree.png',
      '/product-bridal-saree.png',
      '/product-set-mundu.png',
      '/collection-sarees.png',
    ],
    rating: 4.8,
    reviews: 124,
    isNew: true,
    isBestseller: false,
    href: '/products/1',
    sku: 'MD-KKS-001',
    sizes: ['Free Size'],
    color: 'Off White & Gold',
    material: 'Pure Cotton with Kasavu Border',
    work: 'Handloom Weave',
    washCare: 'Gentle hand wash or dry clean',
    itemsIncluded: 'Saree with attached blouse piece',
    description:
      'This elegant Kerala Kasavu saree embodies timeless beauty with its pristine off-white fabric and gleaming golden border. Handcrafted by skilled artisans from the looms of Kerala, each piece is a masterwork of traditional weaving. The luxurious kasavu zari border adds a touch of regality, making it perfect for festivals, weddings, and celebrations. The soft cotton fabric ensures all-day comfort while maintaining an effortlessly graceful drape.',
    highlights: [
      'Authentic Kerala handloom product',
      'Pure cotton body with real kasavu zari',
      'Traditional mundu-style golden border',
      'Breathable and comfortable for all-day wear',
    ],
    recentViews: 1014,
  },
  {
    id: 2,
    name: 'Kanchipuram Silk Saree',
    price: 8999,
    originalPrice: 12999,
    image: '/product-kasavu-saree.png',
    images: [
      '/product-bridal-saree.png',
      '/product-kasavu-saree.png',
      '/collection-festive.png',
      '/collection-sarees.png',
    ],
    rating: 4.9,
    reviews: 89,
    isNew: false,
    isBestseller: true,
    href: '/products/2',
    sku: 'MD-KSS-002',
    sizes: ['Free Size'],
    color: 'Royal Magenta & Gold',
    material: 'Pure Mulberry Silk',
    work: 'Zari Weave with Temple Border',
    washCare: 'Dry clean only',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'A magnificent Kanchipuram silk saree that epitomizes South Indian grandeur. Woven with the finest mulberry silk threads intertwined with real zari, this saree features the iconic temple border pattern that has been a hallmark of Kanchipuram weaving for centuries. The rich magenta hue paired with intricate gold motifs creates a stunning visual masterpiece perfect for bridal trousseaus and grand occasions.',
    highlights: [
      'Authentic Kanchipuram GI tagged product',
      'Pure mulberry silk with real zari',
      'Iconic temple border design',
      'Comes with contrast blouse piece',
    ],
    recentViews: 2347,
  },
  {
    id: 3,
    name: 'Banarasi Silk Saree',
    price: 15999,
    originalPrice: 19999,
    image: '/product-kasavu-saree.png',
    images: [
      '/collection-festive.png',
      '/product-bridal-saree.png',
      '/product-kasavu-saree.png',
      '/collection-sarees.png',
    ],
    rating: 4.7,
    reviews: 156,
    isNew: false,
    isBestseller: true,
    href: '/products/3',
    sku: 'MD-BSS-003',
    sizes: ['Free Size'],
    color: 'Deep Maroon & Antique Gold',
    material: 'Pure Banarasi Silk',
    work: 'Kadwa Weave with Meenakari',
    washCare: 'Dry clean only',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'An exquisite Banarasi silk saree that is the crown jewel of any collection. Handwoven in the ancient city of Varanasi using the traditional kadwa weave technique, this masterpiece features intricate meenakari work with floral jaal patterns across the body. The deep maroon color symbolizes auspiciousness and celebration, making it an ideal choice for weddings, pujas, and grand festivities.',
    highlights: [
      'Handwoven in Varanasi by master weavers',
      'Authentic kadwa weave (not machine-cut)',
      'Meenakari work with gold & silver zari',
      'Heavy pallu with elaborate motifs',
    ],
    recentViews: 876,
  },
  {
    id: 4,
    name: 'Cotton Handloom Saree',
    price: 1299,
    originalPrice: 1799,
    image: '/product-kasavu-saree.png',
    images: [
      '/product-set-mundu.png',
      '/product-kasavu-saree.png',
      '/collection-new.png',
      '/collection-sarees.png',
    ],
    rating: 4.5,
    reviews: 78,
    isNew: true,
    isBestseller: false,
    href: '/products/4',
    sku: 'MD-CHS-004',
    sizes: ['Free Size'],
    color: 'Indigo Blue & White',
    material: 'Pure Handloom Cotton',
    work: 'Block Print',
    washCare: 'Gentle machine wash, cold water',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'A beautifully crafted cotton handloom saree that celebrates the art of traditional Indian block printing. The rich indigo blue base is adorned with delicate white geometric and floral patterns, each stamped by hand using carved wooden blocks. Lightweight and breathable, this saree is your perfect companion for daily elegance, office wear, or casual outings.',
    highlights: [
      'Hand block printed with natural dyes',
      'Lightweight and breathable cotton',
      'Perfect for daily and semi-formal wear',
      'Eco-friendly production process',
    ],
    recentViews: 543,
  },
  {
    id: 5,
    name: 'Mysore Silk Saree',
    price: 5999,
    originalPrice: 7999,
    image: '/product-kasavu-saree.png',
    images: [
      '/collection-sarees.png',
      '/product-bridal-saree.png',
      '/product-kasavu-saree.png',
      '/collection-festive.png',
    ],
    rating: 4.6,
    reviews: 112,
    isNew: false,
    isBestseller: false,
    href: '/products/5',
    sku: 'MD-MSS-005',
    sizes: ['Free Size'],
    color: 'Emerald Green & Gold',
    material: 'Pure Mysore Silk (Crepe)',
    work: 'Zari Border Weave',
    washCare: 'Dry clean recommended',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'The Mysore Silk saree is renowned for its understated elegance and incredible softness. Made from pure Mysore crepe silk with a distinctive sheen, this emerald green beauty features a tasteful gold zari border. The smooth texture and beautiful drape make it a favorite among discerning women who appreciate subtle luxury. A GI-tagged product from the royal looms of Karnataka.',
    highlights: [
      'GI-tagged Mysore Silk',
      'Pure crepe silk with natural sheen',
      'Lightweight with excellent drape',
      'Subtle zari border for understated elegance',
    ],
    recentViews: 728,
  },
  {
    id: 6,
    name: 'Pochampally Ikat Saree',
    price: 4499,
    originalPrice: 5999,
    image: '/product-kasavu-saree.png',
    images: [
      '/collection-new.png',
      '/product-set-mundu.png',
      '/product-kasavu-saree.png',
      '/collection-sarees.png',
    ],
    rating: 4.4,
    reviews: 67,
    isNew: true,
    isBestseller: false,
    href: '/products/6',
    sku: 'MD-PIS-006',
    sizes: ['Free Size'],
    color: 'Teal & Coral Multi',
    material: 'Handloom Silk Cotton',
    work: 'Double Ikat Weave',
    washCare: 'Dry clean only',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'A stunning Pochampally Ikat saree featuring the mesmerizing double-ikat technique from Telangana. Both the warp and weft threads are resist-dyed before weaving, creating the signature blurred-edge geometric patterns that are impossible to replicate by machine. The vibrant teal and coral palette brings a contemporary flair to this centuries-old art form.',
    highlights: [
      'Authentic Pochampally double ikat',
      'UNESCO Intangible Heritage craft',
      'Each piece is unique due to handmade process',
      'Contemporary colors with traditional technique',
    ],
    recentViews: 392,
  },
  {
    id: 7,
    name: 'Chanderi Silk Saree',
    price: 3999,
    originalPrice: 4999,
    image: '/product-kasavu-saree.png',
    images: [
      '/product-kasavu-saree.png',
      '/collection-festive.png',
      '/product-bridal-saree.png',
      '/collection-sarees.png',
    ],
    rating: 4.7,
    reviews: 93,
    isNew: false,
    isBestseller: true,
    href: '/products/7',
    sku: 'MD-CSS-007',
    sizes: ['Free Size'],
    color: 'Pastel Pink & Silver',
    material: 'Chanderi Silk Cotton',
    work: 'Zari Buttis with Border',
    washCare: 'Gentle hand wash or dry clean',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'A delicate Chanderi silk saree that is a symbol of Madhya Pradesh\'s weaving heritage. Known for its sheer texture and lightweight feel, this pastel pink beauty is adorned with shimmering silver zari buttis scattered across the body. The gossamer-like fabric drapes beautifully and is perfect for summer celebrations, festivals, and elegant daytime events.',
    highlights: [
      'Authentic Chanderi from Madhya Pradesh',
      'Signature sheer texture and lightweight',
      'Silver zari buttis with border',
      'Perfect for summer and festive occasions',
    ],
    recentViews: 651,
  },
  {
    id: 8,
    name: 'Paithani Silk Saree',
    price: 18999,
    originalPrice: 24999,
    image: '/product-kasavu-saree.png',
    images: [
      '/product-bridal-saree.png',
      '/collection-festive.png',
      '/product-kasavu-saree.png',
      '/collection-sarees.png',
    ],
    rating: 4.9,
    reviews: 45,
    isNew: false,
    isBestseller: true,
    href: '/products/8',
    sku: 'MD-PSS-008',
    sizes: ['Free Size'],
    color: 'Wine Purple & Gold',
    material: 'Pure Paithani Silk',
    work: 'Peacock Pallu with Muniya Border',
    washCare: 'Dry clean only',
    itemsIncluded: 'Saree with unstitched blouse fabric',
    description:
      'A breathtaking Paithani silk saree from Paithan, Maharashtra — often called the "Queen of Sarees." This wine purple masterpiece features the iconic peacock motif on the pallu, meticulously woven by hand using the tapestry weave technique. The muniya (parrot) border adds another layer of artistry. Each Paithani takes months to complete, making it a true heirloom piece worthy of passing down through generations.',
    highlights: [
      'Handwoven in Paithan, Maharashtra',
      'Iconic peacock pallu design',
      'Tapestry weave technique – months to make',
      'Heirloom quality investment piece',
    ],
    recentViews: 1203,
  },
]

export default allProducts
